#ifndef __ECUGROUPS_H
#define __ECUGROUPS_H

#include "Field.h"

#define FIELDS_PER_GROUP 4
#define NUM_GROUPS 21

// Groups for Simos 2P ECU
Field ECUGroups[NUM_GROUPS][FIELDS_PER_GROUP] = {
  {FIELD_RPM, FIELD_TEMPERATURE, FIELD_L_VOLTAGE, FIELD_BITFIELD_8},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW}
};

#endif
