#ifndef __ECUGROUPS_H
#define __ECUGROUPS_H

#include "Field.h"

#define FIELDS_PER_GROUP 4
#define NUM_GROUPS 21
#define FIRST_GROUP 1

// Groups for Simos 2P ECU
static Field ECUGroups[NUM_GROUPS][FIELDS_PER_GROUP] = {
  {FIELD_RPM, FIELD_TEMPERATURE, FIELD_L_VOLTAGE, FIELD_BITFIELD_8},
  {FIELD_RPM, FIELD_NA, FIELD_SPEED, FIELD_BITFIELD_4},
  {FIELD_RPM, FIELD_NA, FIELD_ANGLE, FIELD_PERCENTAGE},
  {FIELD_RPM, FIELD_NA, FIELD_INJ_TIME, FIELD_NA},
  {FIELD_RPM, FIELD_VOLTAGE, FIELD_TEMPERATURE, FIELD_TEMPERATURE},
  {FIELD_RPM, FIELD_NA, FIELD_ANGLE, FIELD_RAW},

  {FIELD_ANGLE, FIELD_RAW, FIELD_RAW, FIELD_BITFIELD_4},
  {FIELD_RPM, FIELD_RPM, FIELD_PERCENTAGE, FIELD_NA},
  {FIELD_PERCENTAGE, FIELD_BITFIELD_4, FIELD_TEMPERATURE, FIELD_RPM},
  {FIELD_PERCENTAGE, FIELD_L_VOLTAGE, FIELD_PERCENTAGE, FIELD_PERCENTAGE},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},

  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW}
};

#endif
