 #include "ECUGroups.h"
 
 Field ECUGroups[NUM_GROUPS][FIELDS_PER_GROUP] = {
  {FIELD_RPM, FIELD_TEMPERATURE, FIELD_L_VOLTAGE, FIELD_BITFIELD_8},
  {FIELD_RPM, FIELD_NA, FIELD_SPEED, FIELD_BITFIELD_4},
  {FIELD_RPM, FIELD_NA, FIELD_ANGLE, FIELD_PERCENTAGE},
  {FIELD_RPM, FIELD_NA, FIELD_INJ_TIME, FIELD_NA},
  {FIELD_RPM, FIELD_VOLTAGE, FIELD_TEMPERATURE, FIELD_TEMPERATURE},
  {FIELD_RPM, FIELD_NA, FIELD_ANGLE, FIELD_RAW},

  {FIELD_ANGLE, FIELD_RAW, FIELD_RAW, FIELD_BITFIELD_4},
  {FIELD_RPM, FIELD_RPM, FIELD_PERCENTAGE, FIELD_NA},
  {FIELD_PERCENTAGE, FIELD_BITFIELD_4, FIELD_TEMPERATURE, FIELD_RPM},
  {FIELD_PERCENTAGE, FIELD_L_VOLTAGE, FIELD_PERCENTAGE, FIELD_PERCENTAGE},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_BITFIELD_8},
  {FIELD_RPM, FIELD_NA, FIELD_PERCENTAGE, FIELD_L_VOLTAGE},

  {FIELD_RPM, FIELD_NA, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RPM, FIELD_NA, FIELD_RAW, FIELD_RAW},
  {FIELD_RPM, FIELD_NA, FIELD_RAW, FIELD_RAW},
  {FIELD_RAW, FIELD_RAW, FIELD_RAW, FIELD_RAW},
  {FIELD_RPM, FIELD_NA, FIELD_RAW, FIELD_RAW},
  {FIELD_RPM, FIELD_BIT, FIELD_BIT, FIELD_BIT},
  
  {FIELD_RPM, FIELD_NA, FIELD_TEMPERATURE, FIELD_BITFIELD_8},
  {FIELD_BITFIELD_4, FIELD_PERCENTAGE, FIELD_PERCENTAGE, FIELD_PERCENTAGE}
};
